### ISSUE TITLE
<ul> lijsten bevatten niet alleen <li>, <scripts> & <template>

### ISSUE THREAD

**Issue by Amberhva** [r20222/performance-matters-optimized-website#32]
Dit zijn enige drie dingen wat in een `ul` mag komen te staan, verder niks. Dit maakt het anders moeilijker voor de screenreader om de lijsten te lezen.

**Comment by r20222** [comment]
Ik dit gecontroleerd op onze website en zie in de foot.ejs een `<h3>`  tag in een `<ul>` staan. Dit kunnen we misschien nog even aanpassen. 

![image](https://github.com/r20222/performance-matters-optimized-website/assets/101579892/c4821b97-1ce1-4f6c-b551-ff580bc1c475)

Het begint vanaf regel 27 t/m 49.

Ik heb ook even gecontroleerd of er `<a>` tags in een `<li>` mag staan, en dat mag volgens stackoverflow: [https://stackoverflow.com/questions/9627683/a-tag-around-li-tag](url)
